# Generated by Django 5.2.15 on 2026-06-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('candidate_profile', 'job')},
        ),
    ]
