# Generated by Django 5.2.15 on 2026-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
        ('jobs', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('portal', 'TalentAI Portal'), ('linkedin', 'LinkedIn'), ('internshala', 'Internshala')], db_index=True, default='portal', max_length=50),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source', 'status'], name='jobs_job_source_2691b0_idx'),
        ),
    ]
