# Generated by Django 5.2.15 on 2026-06-22 13:06

import django.db.models.deletion
import resumes.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_recruiterprofile_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=resumes.models.resume_upload_path, validators=[resumes.models.validate_pdf])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('is_primary', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('parsed_content', models.JSONField(blank=True, default=dict)),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.candidateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
